122 update angular models
COS301-SE-2023/FridgeToPlate pull request #154
Opened 2023-07-08 20:46 UTC by Shojiki-Lukhozi

# Description

Updated the Angular Models based on revised diagrams. Further revision will be needed to be done on the diagrams as certain issues/matters arose and were rectified.

Fixes # 122

## Type of change

Please delete options that are not relevant.

- [X] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

# Checklist:

- [X] My code follows the style guidelines of this project
- [X I have performed a self-review of my code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules

2023-07-08 21:42 UTC, ryanbasiltrickett requested changes
Please see all requested changes

2023-07-08 21:42 UTC, ryanbasiltrickett commented on libs/app/ingredient/utils/src/interfaces/ingredient.interface.ts
>    ingredientId?: string;
Please follow ingredient model

2023-07-08 21:42 UTC, ryanbasiltrickett commented on libs/app/ingredient/utils/src/interfaces/ingredient.interface.ts
>    tags?: string[];
Please follow ingredient model

2023-07-08 21:42 UTC, ryanbasiltrickett commented on libs/app/meal-plan/utils/src/interfaces/meal-plan.interface.ts
> +  mealplanId?: string;
Please follow meal plan model

2023-07-08 21:42 UTC, ryanbasiltrickett commented on libs/app/meal-plan/utils/src/interfaces/meal-plan.interface.ts
> +  Breakfast: IRecipeDesc | null;
Please follow meal plan model

2023-07-08 21:42 UTC, ryanbasiltrickett commented on libs/app/meal-plan/utils/src/interfaces/meal-plan.interface.ts
> +  Lunch: IRecipeDesc | null;
Please follow meal plan model

2023-07-08 21:42 UTC, ryanbasiltrickett commented on libs/app/meal-plan/utils/src/interfaces/meal-plan.interface.ts
> +  Dinner: IRecipeDesc | null;
Please follow meal plan model

2023-07-08 21:42 UTC, ryanbasiltrickett commented on libs/app/meal-plan/utils/src/interfaces/meal-plan.interface.ts
> +  Snack: IRecipeDesc | null;
Please follow meal plan model

2023-07-08 21:42 UTC, ryanbasiltrickett commented on libs/app/meal-plan/utils/src/interfaces/meal-plan.interface.ts
> +  Dessert: IRecipeDesc | null;
Please follow meal plan model

2023-07-08 21:42 UTC, ryanbasiltrickett commented on libs/app/preference/utils/src/interfaces/preference.interface.ts
> +  userId?: string;
Please follow preferences model

2023-07-08 21:42 UTC, ryanbasiltrickett commented on libs/app/preference/utils/src/interfaces/preference.interface.ts
> +export interface IPreference {
Please follow preferences model naming

2023-07-08 21:42 UTC, ryanbasiltrickett commented on libs/app/preference/utils/src/interfaces/preference.interface.ts
> +  recommendNotification: boolean;
Please follow preferences model

2023-07-08 21:42 UTC, ryanbasiltrickett commented on libs/app/preference/utils/src/interfaces/preference.interface.ts
> +  viewsNotification: boolean;
Please follow preferences model

2023-07-08 21:42 UTC, ryanbasiltrickett commented on libs/app/preference/utils/src/interfaces/preference.interface.ts
> +  reviewsdNotification: boolean;
Please follow preferences model

2023-07-08 21:42 UTC, ryanbasiltrickett commented on libs/app/profile/utils/src/interfaces/profile.interface.ts
> +    profileId?: string;
Please follow profile model

2023-07-08 21:42 UTC, ryanbasiltrickett commented on libs/app/profile/utils/src/interfaces/profile.interface.ts
> +    currMealPlan: IMealPlan[] | null;
Please follow profile model

2023-07-08 21:42 UTC, ryanbasiltrickett commented on libs/app/profile/utils/src/interfaces/profile.interface.ts
> +    preferences: IPreference[];
Please follow profile model

2023-07-08 21:42 UTC, ryanbasiltrickett commented on libs/app/recipe/utils/src/interfaces/recipe.interface.ts
>    tags?: string[];
Please follow recipe description model, shouldn't be optional

2023-07-08 21:42 UTC, ryanbasiltrickett commented on libs/app/recipe/utils/src/interfaces/recipe.interface.ts
> +  description: string;
Please follow recipe model

2023-07-08 21:42 UTC, ryanbasiltrickett commented on libs/app/recipe/utils/src/interfaces/recipe.interface.ts
> +  numberOfServings: number;
Please follow recipe model

2023-07-08 21:42 UTC, ryanbasiltrickett commented on libs/app/review/utils/src/interfaces/review.interface.ts
> +  recipeId?: string;
Please follow review model, shouldn't be optional

2023-07-08 21:55 UTC, ryanbasiltrickett commented
Please add specified tests under the test section of the PR, and add labels, milestone, etc

2023-07-10 20:55 UTC, simphiwe-nonabe approved these changes
Well done, my boy🦥

2023-07-10 20:55 UTC, merged