128 design notification page
COS301-SE-2023/FridgeToPlate pull request #158
Opened 2023-07-11 13:46 UTC by kphutiyagae

# Description

Added Notifications page angular functionality (without NGXS for now)

Fixes # 128 design notification page

## Type of change

Feature

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration.

- [x] Unit tests

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2023-07-11 14:20 UTC, ryanbasiltrickett requested changes

2023-07-11 16:27 UTC, ryanbasiltrickett requested changes
Please revise

2023-07-11 16:27 UTC, ryanbasiltrickett commented on libs/app/notifications/feature/src/notifications.page.html
> +<div class="h-full w-full">
Ensure the background colour is the same as for the application and allow scrollable incase it over flows

2023-07-11 16:27 UTC, ryanbasiltrickett commented on libs/app/notifications/feature/src/notifications.page.html
> +  <div class="h-1/5 w-full flex flex-row items-center">
Add back button

2023-07-11 20:21 UTC, kphutiyagae commented on libs/app/notifications/feature/src/notifications.page.html
> +  <div class="h-1/5 w-full flex flex-row items-center">
Done.

2023-07-11 20:21 UTC, kphutiyagae commented on libs/app/notifications/feature/src/notifications.page.html
> +<div class="h-full w-full">
Done

2023-07-12 16:26 UTC, ryanbasiltrickett approved these changes

2023-07-12 16:26 UTC, merged