133 update navbar
COS301-SE-2023/FridgeToPlate pull request #159
Opened 2023-07-12 22:41 UTC by simphiwe-nonabe

# Description

Refactored top navbar for large (Desktop) display and updated bottom navbar for small (Mobile) and medium (Tablet) display 

Fixes #133 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2023-07-13 10:31 UTC, ryanbasiltrickett requested changes
Add notification page route for Desktop (profile/notifications)

2023-07-16 10:48 UTC, PaulPilane commented
Do not forget to add tests. It is failing because you did not write tests for the added functionality

2023-07-19 17:26 UTC, ryanbasiltrickett requested changes

2023-07-19 17:26 UTC, ryanbasiltrickett commented on libs/app/navigation/feature/src/navigation.component.ts
Where is the route for notifications?

2023-07-19 17:26 UTC, ryanbasiltrickett commented on libs/app/profile/feature/src/profile.page.ts
> +  handleNotificationsClicked() {
Remove these handle clicks please

2023-07-19 17:34 UTC, PaulPilane commented
Also, pull first onto your branch and resolve conflicts

2023-07-20 09:06 UTC, ryanbasiltrickett requested changes

2023-07-20 09:06 UTC, ryanbasiltrickett commented on libs/app/profile/feature/src/profile.page.ts
> +  public getStore(): Store {
Please remove this, there is no need for it

2023-07-20 09:33 UTC, ryanbasiltrickett requested changes

2023-07-20 09:33 UTC, ryanbasiltrickett commented on libs/app/profile/feature/src/profile.page.ts
> +  // handleNotificationsClicked() {
Please remove don't comment out

2023-07-20 09:33 UTC, ryanbasiltrickett commented on libs/app/profile/feature/src/profile.page.spec.ts
> +  //   const openSettingsSpy = jest.spyOn(page, 'openSettings');
Please remove don't comment out

2023-07-20 19:27 UTC, kphutiyagae approved these changes

2023-07-20 19:29 UTC, merged