Notifications ngxs refactor
COS301-SE-2023/FridgeToPlate pull request #168
Opened 2023-07-17 21:15 UTC by kphutiyagae

# Description

Implemented NGXS state management for Notifications feature.

Fixes # 151-refactor-code-for-pubsub

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration.

- [ ] Unit Tests
- [ ] Component Tests

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-07-18 11:40 UTC, ryanbasiltrickett requested changes

2023-07-18 11:40 UTC, ryanbasiltrickett commented on libs/app/notifications/data-access/src/notifications.actions.ts
This file should be in the utils folder under notifications

2023-07-18 11:40 UTC, ryanbasiltrickett commented on libs/app/notifications/utils/src/interfaces/notifications.interface.ts
Please send a small documented overview of these interfaces such that they may be integrated and used else where and approved

2023-07-19 08:32 UTC, kphutiyagae commented on libs/app/notifications/data-access/src/notifications.actions.ts
Done

2023-07-19 08:32 UTC, kphutiyagae commented on libs/app/notifications/utils/src/interfaces/notifications.interface.ts
Will be sent.

2023-07-20 06:50 UTC, ryanbasiltrickett approved these changes

2023-07-20 06:50 UTC, merged