194 incorrect recommend proceedure
COS301-SE-2023/FridgeToPlate pull request #211
Opened 2023-07-29 15:54 UTC by kphutiyagae

# Description

Corrected recommend procedure on both front and back end

Fixes #194-incorrect-recommend-proceedure

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration.

- [ ] Unit tests

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-07-29 17:05 UTC, ryanbasiltrickett requested changes

2023-07-29 17:05 UTC, ryanbasiltrickett commented on libs/app/recommend/data-access/src/recommend.state.ts
> +      this.store.dispatch(
You do not need to update ingredients on the profile they have been deprecated

2023-07-29 17:05 UTC, ryanbasiltrickett commented on libs/app/recommend/data-access/src/recommend.state.ts
> +          //Case 1: User has preferences already - update on store
Should not need to check for no preferences stored. As the user should always have preferences stored after sign up.

2023-07-29 17:37 UTC, kphutiyagae commented on libs/app/recommend/data-access/src/recommend.state.ts
> +      this.store.dispatch(
Done.

2023-07-29 17:42 UTC, kphutiyagae commented on libs/app/recommend/data-access/src/recommend.state.ts
> +          //Case 1: User has preferences already - update on store
Was done to prevent nulls when pulling from DB. But done.

2023-07-29 18:35 UTC, ryanbasiltrickett requested changes

2023-07-29 18:35 UTC, ryanbasiltrickett commented on libs/app/recommend/data-access/src/recommend.state.ts
> +      this.store.dispatch(
No need to update ingredients on profile it has been deprecated. Please remove the action on the profile.

2023-07-29 18:35 UTC, ryanbasiltrickett commented on libs/app/recommend/data-access/src/recommend.state.ts
> +        .updateRecommendations(newRecommendations)
why don't you just pass the recommendRequest object?

2023-07-29 18:35 UTC, ryanbasiltrickett commented on libs/app/recommend/data-access/src/recommend.state.ts
> +        .updateRecommendations(newRecommendations)
why don't you just pass the recommendRequest object?

2023-07-29 18:35 UTC, ryanbasiltrickett commented on libs/app/recommend/data-access/src/recommend.state.ts
> +        .updateRecommendations(newRecommendations)
why don't you just pass the recommendRequest object?

2023-07-29 18:35 UTC, ryanbasiltrickett commented on libs/app/recommend/data-access/src/recommend.state.ts
> +        .updateRecommendations(newRecommendations)
why don't you just pass the recommendRequest object?

2023-07-29 18:35 UTC, ryanbasiltrickett commented on libs/app/recommend/data-access/src/recommend.state.ts
> +        .updateRecommendations(newRecommendations)
why don't you just pass the recommendRequest object?

2023-07-29 21:17 UTC, kphutiyagae commented on libs/app/recommend/data-access/src/recommend.state.ts
> +      this.store.dispatch(
Updated.

2023-07-29 21:19 UTC, kphutiyagae commented on libs/app/recommend/data-access/src/recommend.state.ts
> +        .updateRecommendations(newRecommendations)
Done.

2023-07-30 06:52 UTC, ryanbasiltrickett requested changes

2023-07-30 06:52 UTC, ryanbasiltrickett commented on libs/app/recommend/feature/src/recommend.page.ts
> +    this.store.dispatch(GetUpdatedRecommendation);
Maybe move this to the sign-in part of the auth state, like how the profile is retrieved. Maybe also have a state dispatch to create and save a default recommend request object for when users sign up

2023-07-30 13:55 UTC, kphutiyagae commented on libs/app/recommend/feature/src/recommend.page.ts
> +    this.store.dispatch(GetUpdatedRecommendation);
Done.

2023-07-30 21:24 UTC, ryanbasiltrickett requested changes
Doesn't complete request correctly based on preferences

2023-07-31 04:17 UTC, ryanbasiltrickett approved these changes

2023-07-31 04:17 UTC, merged