Core Setup
COS301-SE-2023/FridgeToPlate pull request #28
Opened 2023-05-17 06:51 UTC by PaulPilane

# Description

Angular core module and routing setup for project, along with the addition of ionic libraries.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Angular app passes all predefined library tests.

- [x] Nx Welcome Test

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2023-05-18 16:11 UTC, kphutiyagae commented on apps/app/src/index.html
> +    <core-shell></core-shell>
Why did we switch from AppModule to CoreModule?

2023-05-18 17:40 UTC, ryanbasiltrickett commented on apps/app/src/index.html
> +    <core-shell></core-shell>
This is just a renaming of the core module component

2023-05-18 17:49 UTC, Shojiki-Lukhozi submitted a review, later dismissed

2023-05-18 17:52 UTC, kphutiyagae requested changes
Please address comments before merge.

2023-05-18 21:22 UTC, ryanbasiltrickett submitted a review, later dismissed

2023-05-19 07:14 UTC, kphutiyagae approved these changes
Looks good, approved.

2023-05-19 08:20 UTC, ryanbasiltrickett approved these changes

2023-05-19 08:20 UTC, merged