295 uiux revised profile
COS301-SE-2023/FridgeToPlate pull request #303
Opened 2023-09-14 23:23 UTC by kphutiyagae

# Description

Aligned Meal plan with cntre axis, changed font weight and added animations to edit-recipe-modal.ts

Fixes # 295

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-09-15 09:22 UTC, PaulPilane commented
Please tick all the relevant checkboxes.

2023-09-15 09:47 UTC, ryanbasiltrickett requested changes
Make changes as requested

2023-09-15 09:55 UTC, Shojiki-Lukhozi approved these changes

2023-09-18 08:12 UTC, ryanbasiltrickett requested changes
Not all GitHub tests running

2023-09-18 21:52 UTC, simphiwe-nonabe approved these changes

2023-09-18 21:53 UTC, ryanbasiltrickett approved these changes

2023-09-18 21:54 UTC, merged