317 bug search page not showing results
COS301-SE-2023/FridgeToPlate pull request #331
Opened 2023-09-20 12:12 UTC by Shojiki-Lukhozi

# Description

Allow User To Search For Recipe

Fixes # (issue) 317 

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] My changes generate no new warnings
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules

2023-09-20 13:19 UTC, ryanbasiltrickett requested changes

2023-09-20 13:19 UTC, ryanbasiltrickett commented on libs/app/core/src/core.module.ts
> +    NgxsModule.forRoot([AuthState, ErrorState, UndoState, InfoState, ProfileState, PreferencesState, RecommendState, ExploreState]),
I'm sure there is another way than having the explore state throughout the app

2023-09-20 13:26 UTC, Shojiki-Lukhozi commented on libs/app/core/src/core.module.ts
> +    NgxsModule.forRoot([AuthState, ErrorState, UndoState, InfoState, ProfileState, PreferencesState, RecommendState, ExploreState]),
This seems the most intuitive way since users should be able to search regardless of a user logging in.

2023-09-20 18:30 UTC, ryanbasiltrickett commented on libs/app/core/src/core.module.ts
> +    NgxsModule.forRoot([AuthState, ErrorState, UndoState, InfoState, ProfileState, PreferencesState, RecommendState, ExploreState]),
That doesn't mean it should be accessible throughout the app. It only needs to be in the explore section

2023-09-20 20:03 UTC, kphutiyagae approved these changes

2023-09-21 03:07 UTC, ryanbasiltrickett approved these changes

2023-09-21 03:17 UTC, merged