365 bug dark mode
COS301-SE-2023/FridgeToPlate pull request #376
Opened 2023-10-09 23:47 UTC by Shojiki-Lukhozi

# Description

Updated Dark Mode To Many Pages In Application

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] My changes generate no new warnings
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules

2023-10-09 23:53 UTC, simphiwe-nonabe submitted a review, later dismissed
Please do requested changes

2023-10-11 11:20 UTC, PaulPilane requested changes
Please resolve conflicts

2023-10-12 05:57 UTC, ryanbasiltrickett requested changes
Perform changes requested

2023-10-13 07:03 UTC, ryanbasiltrickett approved these changes

2023-10-13 07:05 UTC, merged